### ISSUE TITLE
Handle category in store API

### ISSUE THREAD

**Issue by mokuno029238** [wgshtg/authorized_store#22]
# Handle category in store API

## Search stores by category identifiers

- propety: `categoryIds`, category identifiers, are optional
- description: stores should belong to one of categories.

## Create new store with a category

- propety: `categoryId`, category identifier, is optional
- description: create new store with a category.
- others:
    - if the category with specified identifier does not exist, this property will be ignored.

## Update an existing category

- propety: `categoryId`, category identifier, is optional
- description: update a store with specified category.
- others:
    - if the category with specified identifier does not exist, this property will be ignored.
    - if the store belongs to one category and `categoryId` is blank, original category will be removed from the store.

**Comment by wgshtg** [comment]
> Update an existing category
> - others:
>   - if the store belongs to one category and categoryId is blank, then......?

我傾向當 `categoryId` 是空的 => 清除分類。
