### ISSUE TITLE
AuthorizedStore Library 實作查詢條件

### ISSUE THREAD

**Issue by mokuno029923** [wgshtg/authorized_store#5]
目前僅實作分頁機制。

實作 Criteria 剩餘查詢條件

1. `Name`：名稱，支援模糊查詢，不支援特殊字元查詢。
- 特殊字元：`!`、`@`、`#`、`$`、`%`、`^`、`&`、`*`、`,`、`;`、`:`、`>`、`<`、`?`、`+`、`=`、`{`、`}`、`[`、`]`、`\`、`|`、`"`、`'`、`.`、`/`、`~`、`_`、`` ` ``、`(`、`)`。
- 查詢條件僅包含空白字元，視為查詢所有商店。
- 例如：查詢 `Ma[特殊字元]tt`，回傳不合法字元錯誤。
- 例如：查詢 `Matt`，商店名稱 `Matt Store` 會符合結果。
- 例如：查詢 `Matt Store`，商店名稱 `Matt Store` 會符合結果。
2. `CategoryId`：類別 ID。
- 擴充類別查詢改為複數、擁有任一類別會符合結果。
3. `ContractStartDate`：合約生效起始日。
- 若商店合約生效結束日 >= `ContractStartDate`，會符合結果。
- 若 `ContractStartDate` 有值，`ContractEndDate` < `ContractStartDate` 或為空，則 `ContractEndDate` 要設為 `ContractStartDate`。
4. `ContractEndDate`：合約生效結束日。
- 若商店合約生效起始日 <= `ContractEndDate`，會符合結果。
- 若 `ContractEndDate` 有值，`ContractStartDate` > `ContractEndDate` 或為空，則 `ContractStartDate` 要設為 `ContractEndDate`。

**Comment by wgshtg** [comment]
> ContractStartDate > ContractEndDate 時，throw exception

同意用例外處理。

**Comment by mokuno029238** [comment]
> 查詢條件新增 CategoryId 查詢，會等 #15 實作後，再添加。
> 建議屆時另外開議題處理。

已建立，請參考 #22。
